#pragma once

#include <SDL3/SDL.h>

#include <array>
#include <atomic>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <memory>
#include <mutex>
#include <set>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include "compare/CompareModel.h"
#include "compare/MergeModel.h"
#include "editor/EditorViewRenderer.h"
#include "editor/HighlightPrefetchService.h"
#include "editor/TextViewport.h"
#include "plugin/PluginHost.h"
#include "platform/FileIndexWatcher.h"
#include "project/DirectoryTree.h"
#include "project/FileFinder.h"
#include "project/GitBlameService.h"
#include "project/ProjectBackgroundExecutor.h"
#include "project/FileIndex.h"
#include "project/GitRepositoryMetadataTracker.h"
#include "project/ProjectChangeCoalescer.h"
#include "project/GitCompareService.h"
#include "project/ProjectSearchService.h"
#include "render/SurfaceTextureCache.h"
#include "render/TextRenderer.h"
#include "render/Theme.h"
#include "terminal/TerminalSession.h"
#include "workspace/WorkspaceLayout.h"
#include "workspace/WorkspaceActionAvailability.h"
#include "workspace/WorkspaceActionTypes.h"
#include "workspace/WorkspaceContext.h"
#include "workspace/WorkspaceKeybindingRegistry.h"
#include "workspace/WorkspaceFormatterRegistry.h"
#include "workspace/WorkspaceSaveParticipants.h"
#include "workspace/WorkspaceCompletionRegistry.h"
#include "workspace/WorkspaceCodeActionRegistry.h"
#include "workspace/WorkspaceToolRegistry.h"
#include "workspace/WorkspaceToolDownloader.h"
#include "workspace/WorkspaceLspManager.h"
#include "workspace/WorkspaceTestController.h"
#include "workspace/WorkspaceScmRegistry.h"
#include "workspace/WorkspaceAnnotationRegistry.h"
#include "workspace/WorkspaceThemeRegistry.h"
#include "workspace/WorkspaceFileIconRegistry.h"
#include "workspace/PluginEditorEventTracker.h"
#include "workspace/WorkspaceVirtualDocument.h"
#include "workspace/WorkspaceReviewComments.h"
#include "workspace/WorkspaceEventResult.h"
#include "workspace/AssistService.h"
#include "workspace/ControlChannelService.h"
#include "workspace/ControlSpec.h"
#include "workspace/DebugService.h"
#include "workspace/LspService.h"
#include "workspace/EditorBlameOverlayService.h"
#include "workspace/WorkspaceInteractionState.h"
#include "workspace/WorkspaceMenuState.h"
#include "workspace/WorkspaceMenuRegistry.h"
#include "workspace/LayoutModeService.h"
#include "workspace/GitRepositoryService.h"
#include "workspace/CommitWorkflowService.h"
#include "workspace/NotificationService.h"
#include "workspace/PatchApplyService.h"
#include "workspace/PersistenceService.h"
#include "workspace/RecentsService.h"
#include "workspace/SettingsOverlayService.h"
#include "workspace/SettingsStore.h"
#include "workspace/StatusBarModelService.h"
#include "workspace/StatusBarService.h"
#include "workspace/TabStripService.h"
#include "workspace/WorkspaceTabStripChrome.h"
#include "workspace/WorkspacePersistenceFormat.h"
#include "workspace/WorkspaceOutputChannels.h"
#include "workspace/WorkspaceLanguageContract.h"
#include "workspace/WorkspacePluginReloadRequest.h"
#include "workspace/WorkspacePluginRuntime.h"
#include "workspace/WorkspaceProjectFileMonitor.h"
#include "workspace/WorkspaceProjectDialogState.h"
#include "workspace/WorkspaceProjectState.h"
#include "workspace/DebugPaneRegistry.h"
#include "workspace/DebugPaneService.h"
#include "workspace/WorkspaceProjectSearchRuntime.h"
#include "workspace/WorkspacePromptState.h"
#include "workspace/RenderViewModelBuilder.h"
#include "workspace/WorkspaceRootView.h"
#include "workspace/WorkspaceStatusRegistry.h"
#include "workspace/WorkspaceSidebarState.h"
#include "workspace/WorkspaceStartupOptions.h"
#include "workspace/WorkspaceTerminalSelection.h"
#include "workspace/WorkspaceTextInputState.h"

namespace microide::workspace {

class WorkspaceActionContext;
class PromptSurfaceService;
class ProjectCatalogService;
class PersistenceCoordinator;
class CommandPromptCoordinator;
class MenuCoordinator;
class KeyInputCoordinator;
class TextInputCoordinator;
class EditorTabService;
class TabCoordinator;
class PathMutationCoordinator;
class LifecycleCoordinator;
class DirtyPromptCoordinator;
class CompareInteractionCoordinator;
class DiffTabCoordinator;
class CompareMergeService;
class TerminalPanelService;
class SidebarCoordinator;
class SidebarService;
class ChromeMouseCoordinator;
class EditorMouseCoordinator;
class CompareMouseCoordinator;
class MergeMouseCoordinator;
class TabMouseCoordinator;
class SidebarMouseCoordinator;
class PanelMouseCoordinator;
class DebugPaneMouseCoordinator;

class WorkspaceShell {
#include "workspace/WorkspaceShellMembers.inc"
};

}  // namespace microide::workspace
