#include "workspace/registries/WorkspaceCommandRegistry.h"

#include <algorithm>
#include <array>

namespace microide::workspace {

std::span<const ActionSpec> WorkspaceCommandSpecs() {
  static const auto kSpecs = std::to_array<ActionSpec>({
      ActionSpec{ActionId::CodeActions, "code-actions", "code-actions", "Code Actions",
                 "Ctrl+."},
      ActionSpec{ActionId::FormatDocument, "format-document", "format-document", "Format Document",
                 "Ctrl+Shift+I"},
      ActionSpec{ActionId::FormatJson, "format-json", "format-json [path]", "Format JSON", ""},
      ActionSpec{ActionId::RenameSymbol, "rename-symbol", "rename-symbol", "Rename Symbol", "F2"},
      ActionSpec{ActionId::OpenCommandPalette, "command-palette", "command-palette",
                 "Command Palette…", "Ctrl+Shift+P"},
      ActionSpec{ActionId::Colorscheme, "colorscheme", "colorscheme [name|list]",
                 "Colorscheme", ""},
      ActionSpec{ActionId::ToggleColorTheme, "toggle-theme", "toggle-theme",
                 "Toggle Light/Dark Theme", ""},
      // No default chord: VS Code binds this to F11, but F11 is already
      // `debug-step-in` here and this keybinding model has no when-clause to
      // scope one chord to an active debug session. Menu + command only.
      ActionSpec{ActionId::ToggleFullscreen, "toggle-fullscreen", "toggle-fullscreen",
                 "Toggle Full Screen", ""},
      ActionSpec{ActionId::Completion, "completion", "completion", "Completions",
                 "Ctrl+Space"},
      ActionSpec{ActionId::InsertSnippet, "insert-snippet", "insert-snippet", "Insert Snippet…",
                 "Ctrl+Alt+J"},
      ActionSpec{ActionId::Compare, "compare", "compare [path] [commit-prefix]",
                 "Compare with Git Revision…", ""},
      ActionSpec{ActionId::CompareHead, "", "", "Compare with HEAD", ""},
      ActionSpec{ActionId::CompareFiles, "compare-files", "compare-files <left> <right>",
                 "Compare Files…", ""},
      ActionSpec{ActionId::SelectForCompare, "", "", "Select for Compare", ""},
      ActionSpec{ActionId::CompareWithSelected, "", "", "Compare with Selected", ""},
      ActionSpec{ActionId::CompareWithClipboard, "compare-clipboard", "compare-clipboard",
                 "Compare with Clipboard", ""},
      ActionSpec{ActionId::Merge, "merge", "merge <base> <incoming> <current> [output]",
                 "Open Merge Editor", ""},
      ActionSpec{ActionId::ReviewConflicts, "review-conflicts", "review-conflicts",
                 "Open Merge Conflicts for Review", ""},
      ActionSpec{ActionId::ReviewBranch, "review-branch", "review-branch [ref]",
                 "Review Diff Against Ref", ""},
      ActionSpec{ActionId::ReviewCommit, "review-commit", "review-commit [commit]",
                 "Review Commit Diff", ""},
      ActionSpec{ActionId::ShowInFileExplorer, "", "", "Show in File Explorer", ""},
      ActionSpec{ActionId::RevealInFileTree, "reveal-in-tree", "reveal-in-tree",
                 "Reveal in File Tree", ""},
      ActionSpec{ActionId::CopyAbsolutePath, "", "", "Copy Absolute Path", ""},
      ActionSpec{ActionId::CopyRelativePath, "", "", "Copy Relative Path", ""},
      ActionSpec{ActionId::CreateDirectory, "", "", "New Folder…", ""},
      ActionSpec{ActionId::CreateFile, "", "", "New File…", ""},
      ActionSpec{ActionId::DeletePath, "", "", "Delete…", ""},
      ActionSpec{ActionId::Files, "files", "files [root]", "Go to File…", "Ctrl+P"},
      ActionSpec{ActionId::Find, "find", "find <query>", "Find File by Query", ""},
      ActionSpec{ActionId::FindReferences, "find-references", "find-references",
                 "Find References", "Shift+F12"},
      ActionSpec{ActionId::CallHierarchy, "call-hierarchy", "call-hierarchy [incoming|outgoing]",
                 "Show Call Hierarchy", ""},
      ActionSpec{ActionId::Focus, "focus", "focus <editor|sidebar|panel>", "Focus", ""},
      ActionSpec{ActionId::GoToDefinition, "goto-definition", "goto-definition",
                 "Go to Definition", "F12"},
      ActionSpec{ActionId::GoToTypeDefinition, "goto-type-definition", "goto-type-definition",
                 "Go to Type Definition", ""},
      ActionSpec{ActionId::GoToImplementation, "goto-implementation", "goto-implementation",
                 "Go to Implementation", "Ctrl+F12"},
      ActionSpec{ActionId::GoToDeclaration, "goto-declaration", "goto-declaration",
                 "Go to Declaration", ""},
      ActionSpec{ActionId::WorkspaceSymbol, "workspace-symbol", "workspace-symbol <query>",
                 "Search Workspace Symbols…", ""},
      ActionSpec{ActionId::SignatureHelp, "signature-help", "signature-help",
                 "Signature Help", "Ctrl+Shift+Space"},
      ActionSpec{ActionId::Goto, "goto", "goto <line[:col]>", "Go to Line…", "Ctrl+G"},
      ActionSpec{ActionId::GitRefresh, "git-refresh", "git-refresh", "Git: Refresh", ""},
      ActionSpec{ActionId::GitSwitchBranch, "git-switch-branch", "git-switch-branch [branch]",
                 "Git: Switch Branch…", ""},
      ActionSpec{ActionId::GitCreateBranch, "git-create-branch",
                 "git-create-branch <name> [start-point]", "Git: Create Branch…", ""},
      ActionSpec{ActionId::GitFetch, "git-fetch", "git-fetch", "Git: Fetch", ""},
      ActionSpec{ActionId::GitPull, "git-pull", "git-pull", "Git: Pull", ""},
      ActionSpec{ActionId::GitPush, "git-push", "git-push", "Git: Push", ""},
      ActionSpec{ActionId::GitPublishBranch, "git-publish-branch", "git-publish-branch",
                 "Git: Publish Branch", ""},
      ActionSpec{ActionId::GitSync, "git-sync", "git-sync", "Git: Sync (Pull then Push)", ""},
      ActionSpec{ActionId::GitStash, "git-stash", "git-stash [message]", "Git: Stash Changes", ""},
      ActionSpec{ActionId::GitStashPop, "git-stash-pop", "git-stash-pop", "Git: Pop Stash", ""},
      ActionSpec{ActionId::TerminalFind, "terminal-find", "terminal-find [query]",
                 "Terminal: Find in Scrollback", ""},
      ActionSpec{ActionId::MarkBranchFileReviewed, "mark-branch-file-reviewed",
                 "mark-branch-file-reviewed", "Mark Branch File Reviewed", ""},
      ActionSpec{ActionId::UnmarkBranchFileReviewed, "unmark-branch-file-reviewed",
                 "unmark-branch-file-reviewed", "Unmark Branch File Reviewed", ""},
      ActionSpec{ActionId::MarkBranchHunkReviewed, "mark-branch-hunk-reviewed",
                 "mark-branch-hunk-reviewed", "Mark Branch Hunk Reviewed", ""},
      ActionSpec{ActionId::UnmarkBranchHunkReviewed, "unmark-branch-hunk-reviewed",
                 "unmark-branch-hunk-reviewed", "Unmark Branch Hunk Reviewed", ""},
      ActionSpec{ActionId::ClearBranchReviewState, "clear-branch-review-state",
                 "clear-branch-review-state", "Clear Branch Review State", ""},
      ActionSpec{ActionId::EditBranchReviewNote, "branch-review-note",
                 "branch-review-note <text>", "Edit Branch Review Note", ""},
      ActionSpec{ActionId::IndentWidth, "indent-width", "indent-width [n]", "Indent Width", ""},
      ActionSpec{ActionId::Jump, "jump", "jump <line[:col]>", "Jump Relative…", ""},
      ActionSpec{ActionId::Open, "open", "open <path>", "Open File…", ""},
      ActionSpec{ActionId::OpenSelectedTreeItem, "", "", "Open", ""},
      ActionSpec{ActionId::OpenSelectedTreeItemInNewTab, "", "", "Open in New Tab", ""},
      ActionSpec{ActionId::OpenHelpAbout, "about", "about", "Help", ""},
      ActionSpec{ActionId::OpenKeyboardShortcuts, "keyboard-shortcuts", "keyboard-shortcuts",
                 "Keyboard Shortcuts", ""},
      ActionSpec{ActionId::OpenSettings, "settings", "settings", "Settings…", "Ctrl+,"},
      ActionSpec{ActionId::ProjectClose, "project-close", "project-close", "Close Project", ""},
      ActionSpec{ActionId::ProjectCopyAbsolutePath, "", "", "Copy Absolute Path", ""},
      ActionSpec{ActionId::ProjectNext, "project-next", "project-next", "Next Project", ""},
      ActionSpec{ActionId::ProjectOpen, "project-open", "project-open [path]", "Open Folder…",
                 ""},
      ActionSpec{ActionId::ProjectPrev, "project-prev", "project-prev", "Previous Project", ""},
      ActionSpec{ActionId::ProjectSearch, "project-search", "project-search [query]",
                 "Find in Project…",
                                 "Ctrl+Shift+F"},
      ActionSpec{ActionId::PluginsReload, "plugins-reload", "plugins-reload", "Reload Plugins",
                 ""},
      ActionSpec{ActionId::DebugToggleEnabled, "debug-toggle-enabled", "debug-toggle-enabled",
                 "Enable Debugger", "", true},
      ActionSpec{ActionId::StartDebugging, "debug-start", "debug-start", "Start Debugging", "F8"},
      ActionSpec{ActionId::StopDebugging, "debug-stop", "debug-stop", "Stop Debugging", ""},
      ActionSpec{ActionId::DebugContinue, "debug-continue", "debug-continue", "Continue", "F5"},
      ActionSpec{ActionId::DebugStepOver, "debug-step-over", "debug-step-over", "Step Over", "F10"},
      ActionSpec{ActionId::DebugStepIn, "debug-step-in", "debug-step-in", "Step In", "F11"},
      ActionSpec{ActionId::DebugStepOut, "debug-step-out", "debug-step-out", "Step Out",
                 "Shift+F11"},
      ActionSpec{ActionId::DebugPause, "debug-pause", "debug-pause", "Pause", "F6"},
      ActionSpec{ActionId::DebugReverseContinue, "debug-reverse-continue",
                 "debug-reverse-continue", "Reverse Continue", ""},
      ActionSpec{ActionId::DebugStepBack, "debug-step-back", "debug-step-back", "Step Back", ""},
      ActionSpec{ActionId::DebugRestart, "debug-restart", "debug-restart", "Restart Debugging",
                 "Ctrl+Shift+F5"},
      ActionSpec{ActionId::DebugSwitchSession, "debug-switch-session", "debug-switch-session [n]",
                 "Switch Debug Session", ""},
      ActionSpec{ActionId::DebugStopAllSessions, "debug-stop-all", "debug-stop-all",
                 "Stop All Debug Sessions", ""},
      ActionSpec{ActionId::DebugConsoleRepl, "debug-repl", "debug-repl", "Evaluate in Debug Console…",
                 ""},
      ActionSpec{ActionId::PickLaunchConfig, "debug-pick-config", "debug-pick-config",
                 "Select Launch Configuration…", ""},
      ActionSpec{ActionId::DebugPaneToggle, "debug-pane-toggle", "debug-pane-toggle",
                 "Toggle Debug Pane", "Ctrl+Shift+D", true},
      ActionSpec{ActionId::DebugPaneShowCallStack, "debug-pane-callstack", "debug-pane-callstack",
                 "Show Call Stack", ""},
      ActionSpec{ActionId::DebugPaneShowVariables, "debug-pane-variables", "debug-pane-variables",
                 "Show Variables", ""},
      ActionSpec{ActionId::DebugPaneShowWatch, "debug-pane-watch", "debug-pane-watch",
                 "Show Watch", ""},
      ActionSpec{ActionId::DebugPaneShowBreakpoints, "debug-pane-breakpoints",
                 "debug-pane-breakpoints", "Show Breakpoints", ""},
      ActionSpec{ActionId::DebugShowOutput, "debug-show-output", "debug-show-output",
                 "Show Debug Output", "Ctrl+Shift+5"},
      ActionSpec{ActionId::BreakpointSet, "breakpoint-set",
                 "breakpoint-set <file> <line> [condition]", "Set Breakpoint", ""},
      ActionSpec{ActionId::BreakpointRemove, "breakpoint-remove",
                 "breakpoint-remove <file> <line>", "Remove Breakpoint", ""},
      ActionSpec{ActionId::BreakpointEnable, "breakpoint-enable",
                 "breakpoint-enable <file> <line>", "Enable Breakpoint", ""},
      ActionSpec{ActionId::BreakpointDisable, "breakpoint-disable",
                 "breakpoint-disable <file> <line>", "Disable Breakpoint", ""},
      ActionSpec{ActionId::BreakpointCondition, "breakpoint-condition",
                 "breakpoint-condition <file> <line> [expr]", "Set Breakpoint Condition", ""},
      ActionSpec{ActionId::BreakpointHitCondition, "breakpoint-hit-condition",
                 "breakpoint-hit-condition <file> <line> [expr]", "Set Breakpoint Hit Count", ""},
      ActionSpec{ActionId::BreakpointLogMessage, "breakpoint-logmessage",
                 "breakpoint-logmessage <file> <line> [message]", "Set Breakpoint Log Message", ""},
      ActionSpec{ActionId::BreakpointClear, "breakpoint-clear", "breakpoint-clear [file]",
                 "Clear Breakpoints", ""},
      ActionSpec{ActionId::BreakpointFunctionAdd, "breakpoint-function-add",
                 "breakpoint-function-add <name>", "Add Function Breakpoint", ""},
      ActionSpec{ActionId::BreakpointFunctionRemove, "breakpoint-function-remove",
                 "breakpoint-function-remove <name>", "Remove Function Breakpoint", ""},
      ActionSpec{ActionId::BreakpointFunctionToggle, "breakpoint-function-toggle",
                 "breakpoint-function-toggle <name>", "Toggle Function Breakpoint", ""},
      ActionSpec{ActionId::BreakpointFunctionCondition, "breakpoint-function-condition",
                 "breakpoint-function-condition <name> [expr]", "Set Function Breakpoint Condition",
                 ""},
      ActionSpec{ActionId::BreakpointExceptionCondition, "breakpoint-exception-condition",
                 "breakpoint-exception-condition <filterId> [expr]", "Set Exception Condition", ""},
      ActionSpec{ActionId::DebugLaunch, "debug-launch", "debug-launch [name]",
                 "Start Debugging (Launch Config)", ""},
      ActionSpec{ActionId::DebugRun, "debug-run", "debug-run [--type <adapter>] <program> [args...]",
                 "Start Debugging (Program)", ""},
      ActionSpec{ActionId::SetSetting, "set-setting", "set-setting <id> <value>", "Set Setting",
                 ""},
      ActionSpec{ActionId::Quit, "quit", "quit", "Quit", ""},
      ActionSpec{ActionId::RenamePath, "", "", "Rename…", ""},
      ActionSpec{ActionId::Reopen, "reopen", "reopen", "Reopen", ""},
      ActionSpec{ActionId::Save, "save", "save", "Save", "Ctrl+S"},
      ActionSpec{ActionId::Search, "search", "search <query>", "Find in Buffer", "Ctrl+F"},
      ActionSpec{ActionId::SidebarClose, "sidebar-close", "sidebar-close", "Close Sidebar", ""},
      ActionSpec{ActionId::SidebarHide, "sidebar-hide", "sidebar-hide", "Hide Sidebar", ""},
      ActionSpec{ActionId::SidebarShow, "sidebar-show", "sidebar-show [tool]", "Show Sidebar",
                 ""},
      ActionSpec{ActionId::SidebarToggle, "sidebar-toggle", "sidebar-toggle [tool]",
                 "Toggle Sidebar", "Ctrl+B", true},
      ActionSpec{ActionId::SidebarWidth, "sidebar-width", "sidebar-width <n>", "Sidebar Width",
                 ""},
      ActionSpec{ActionId::SoftTabs, "soft-tabs", "soft-tabs [on|off]", "Soft Tabs", ""},
      ActionSpec{ActionId::Wrap, "wrap", "wrap [on|off]", "Word Wrap", "", true},
      ActionSpec{ActionId::Tab, "tab", "tab [path]", "New Text File", ""},
      ActionSpec{ActionId::TabSize, "tab-size", "tab-size [n]", "Tab Size", ""},
      ActionSpec{ActionId::TabMove, "tabmove", "tabmove <n>", "Move Tab", ""},
      ActionSpec{ActionId::TabSwitch, "tabswitch", "tabswitch <tab|+n|-n>", "Switch Tab", ""},
      ActionSpec{ActionId::Term, "term", "term [command]", "New Terminal", ""},
      ActionSpec{ActionId::TermClose, "term-close", "term-close", "Close Terminal", ""},
      ActionSpec{ActionId::TestsDiscover, "tests-discover", "tests-discover",
                 "Discover Tests", ""},
      ActionSpec{ActionId::TestsRun, "tests-run", "tests-run [test-id...]", "Run Tests", ""},
      ActionSpec{ActionId::Tree, "tree", "tree [root]", "Show Tree", ""},
      ActionSpec{ActionId::TreeRefresh, "tree-refresh", "tree-refresh", "Refresh Tree", ""},
      ActionSpec{ActionId::UiScale, "ui-scale", "ui-scale [n|up|down|reset]", "UI Scale", ""},
      ActionSpec{ActionId::ToggleLayoutMode, "layout-mode-toggle", "layout-mode-toggle",
                 "Toggle Layout Mode", ""},
      ActionSpec{ActionId::ToggleStatusBar, "status-bar-toggle", "status-bar-toggle",
                 "Toggle Status Bar", "", true},
      ActionSpec{ActionId::SplitEditorRight, "split-right", "split-right [path]",
                 "Split Editor Right", ""},
      ActionSpec{ActionId::SplitEditorDown, "split-down", "split-down [path]",
                 "Split Editor Down", ""},
      ActionSpec{ActionId::FocusOtherGroup, "focus-other-group", "focus-other-group",
                 "Focus Other Editor Group", ""},
      ActionSpec{ActionId::CloseGroup, "close-group", "close-group", "Close Editor Group", ""},
      ActionSpec{ActionId::CloseActiveTab, "", "", "Close Tab", "Ctrl+W"},
      ActionSpec{ActionId::CloseAllTabs, "", "", "Close All Tabs", ""},
      ActionSpec{ActionId::CloseOtherTabs, "", "", "Close Other Tabs", ""},
      ActionSpec{ActionId::CloseTabsToRight, "", "", "Close Tabs to the Right", ""},
      ActionSpec{ActionId::CloseTabsToLeft, "", "", "Close Tabs to the Left", ""},
      ActionSpec{ActionId::CopyLastTerminalCommand, "", "", "Copy Last Command and Output", ""},
      // These clipboard/history/select verbs carry a command name so they are
      // reachable over the command line and the control channel (headless /
      // LLM-driven control), not just via their keyboard accelerators.
      ActionSpec{ActionId::CopySelection, "copy", "copy", "Copy", "Ctrl+C"},
      ActionSpec{ActionId::CopySelectionWithContext, "", "", "Copy with Context", ""},
      ActionSpec{ActionId::CutSelection, "cut", "cut", "Cut", "Ctrl+X"},
      ActionSpec{ActionId::PasteClipboard, "paste", "paste", "Paste", "Ctrl+V"},
      ActionSpec{ActionId::Redo, "redo", "redo", "Redo", "Ctrl+Y / Ctrl+Shift+Z"},
      ActionSpec{ActionId::ReplaceInBuffer, "", "", "Replace in Buffer", "Ctrl+H"},
      ActionSpec{ActionId::InsertText, "type", "type <text>", "Insert Text", ""},
      ActionSpec{ActionId::SelectAll, "select-all", "select-all", "Select All", "Ctrl+A"},
      ActionSpec{ActionId::Undo, "undo", "undo", "Undo", "Ctrl+Z"},
      ActionSpec{ActionId::JumpToMatchingBracket, "jump-to-matching-bracket",
                 "jump-to-matching-bracket", "Jump to Matching Bracket", "Ctrl+Shift+\\"},
      ActionSpec{ActionId::ToggleLineComment, "toggle-line-comment", "toggle-line-comment",
                 "Toggle Line Comment", "Ctrl+/"},
      ActionSpec{ActionId::ToggleBlockComment, "toggle-block-comment", "toggle-block-comment",
                 "Toggle Block Comment", "Shift+Alt+A"},
      ActionSpec{ActionId::MoveLineUp, "move-line-up", "move-line-up", "Move Line Up", "Alt+Up"},
      ActionSpec{ActionId::MoveLineDown, "move-line-down", "move-line-down", "Move Line Down",
                 "Alt+Down"},
      ActionSpec{ActionId::DuplicateLine, "duplicate-line", "duplicate-line",
                 "Duplicate Selection", "Shift+Alt+Down"},
      ActionSpec{ActionId::DeleteLine, "delete-line", "delete-line", "Delete Line",
                 "Ctrl+Shift+K"},
      ActionSpec{ActionId::IndentLines, "indent-lines", "indent-lines", "Indent Lines", "Tab"},
      ActionSpec{ActionId::OutdentLines, "outdent-lines", "outdent-lines", "Outdent Lines",
                 "Shift+Tab"},
      ActionSpec{ActionId::SortLinesAscending, "sort-lines-ascending", "sort-lines-ascending",
                 "Sort Lines Ascending", ""},
      ActionSpec{ActionId::SortLinesDescending, "sort-lines-descending", "sort-lines-descending",
                 "Sort Lines Descending", ""},
      ActionSpec{ActionId::AddCursorAtNextMatch, "add-cursor-next-match", "add-cursor-next-match",
                 "Add Cursor at Next Match", "Ctrl+D"},
      ActionSpec{ActionId::AddCursorAtAllMatches, "add-cursor-all-matches",
                 "add-cursor-all-matches", "Add Cursor at All Matches", "Ctrl+Shift+L"},
      ActionSpec{ActionId::Fold, "fold", "fold", "Fold", "Ctrl+Shift+["},
      ActionSpec{ActionId::Unfold, "unfold", "unfold", "Unfold", "Ctrl+Shift+]"},
      ActionSpec{ActionId::FoldAll, "fold-all", "fold-all", "Fold All", "Ctrl+K Ctrl+0"},
      ActionSpec{ActionId::UnfoldAll, "unfold-all", "unfold-all", "Unfold All", "Ctrl+K Ctrl+J"},
      ActionSpec{ActionId::ToggleFoldAtCursor, "toggle-fold", "toggle-fold",
                 "Toggle Fold at Cursor", ""},
      ActionSpec{ActionId::ToggleEditorFolding, "toggle-editor-folding", "toggle-editor-folding",
                 "Code Folding", "", true},
      ActionSpec{ActionId::ToggleEditorStickyScroll, "toggle-editor-sticky-scroll",
                 "toggle-editor-sticky-scroll", "Sticky Scroll", "", true},
      ActionSpec{ActionId::ToggleEditorIndentGuides, "toggle-editor-indent-guides",
                 "toggle-editor-indent-guides", "Indent Guides", "", true},
      ActionSpec{ActionId::ToggleEditorRenderWhitespace, "toggle-editor-render-whitespace",
                 "toggle-editor-render-whitespace", "Render Whitespace", "", true},
      ActionSpec{ActionId::ToggleEditorBracketMatchHighlight,
                 "toggle-editor-bracket-match-highlight",
                 "toggle-editor-bracket-match-highlight", "Bracket Match Highlight", "", true},
      ActionSpec{ActionId::ToggleEditorAutoClosePairs, "toggle-editor-auto-close",
                 "toggle-editor-auto-close", "Auto-Close Pairs", "", true},
      ActionSpec{ActionId::ToggleEditorSurround, "toggle-editor-surround",
                 "toggle-editor-surround", "Surround Selection", "", true},
      ActionSpec{ActionId::ToggleEditorSmartIndent, "toggle-editor-smart-indent",
                 "toggle-editor-smart-indent", "Smart Indent", "", true},
      ActionSpec{ActionId::ToggleEditorToggleComment, "toggle-editor-toggle-comment",
                 "toggle-editor-toggle-comment", "Toggle Comment Action", "", true},
      ActionSpec{ActionId::ToggleEditorLineOps, "toggle-editor-line-ops",
                 "toggle-editor-line-ops", "Line Move/Duplicate/Delete", "", true},
      ActionSpec{ActionId::ToggleEditorSortLines, "toggle-editor-sort-lines",
                 "toggle-editor-sort-lines", "Sort Lines Action", "", true},
      ActionSpec{ActionId::ToggleEditorAddCursorAtMatch, "toggle-editor-add-cursor-at-match",
                 "toggle-editor-add-cursor-at-match", "Add Cursor at Match", "", true},
      ActionSpec{ActionId::ToggleEditorOccurrencesHighlight,
                 "toggle-editor-occurrences-highlight",
                 "toggle-editor-occurrences-highlight", "Occurrences Highlight", "", true},
      ActionSpec{ActionId::ToggleEditorSearchCaseSensitive,
                 "toggle-editor-search-case-sensitive",
                 "toggle-editor-search-case-sensitive", "Case-Sensitive Search Seeds", "", true},
      ActionSpec{ActionId::ToggleEditorSnippets, "toggle-editor-snippets",
                 "toggle-editor-snippets", "Snippets", "", true},
      ActionSpec{ActionId::ToggleEditorSaveTrim, "toggle-editor-save-trim",
                 "toggle-editor-save-trim", "Trim Trailing Whitespace on Save", "", true},
      ActionSpec{ActionId::ToggleEditorSaveEnsureNewline, "toggle-editor-save-ensure-newline",
                 "toggle-editor-save-ensure-newline", "Ensure Final Newline on Save", "", true},
      ActionSpec{ActionId::ToggleEditorAutoDetectIndent, "toggle-editor-auto-detect-indent",
                 "toggle-editor-auto-detect-indent", "Auto-Detect Indent on Open", "", true},
  });
  return kSpecs;
}

const ActionSpec* FindWorkspaceActionSpec(ActionId id) {
  const auto specs = WorkspaceCommandSpecs();
  const auto it =
      std::find_if(specs.begin(), specs.end(), [id](const ActionSpec& spec) { return spec.id == id; });
  return it == specs.end() ? nullptr : &(*it);
}

const ActionSpec* FindWorkspaceActionByCommand(std::string_view command_name) {
  const auto specs = WorkspaceCommandSpecs();
  const auto it = std::find_if(specs.begin(), specs.end(), [command_name](const ActionSpec& spec) {
    return !spec.command_name.empty() && spec.command_name == command_name;
  });
  return it == specs.end() ? nullptr : &(*it);
}

const std::vector<std::string>& WorkspaceCommandNames() {
  static const std::vector<std::string> kNames = [] {
    std::vector<std::string> names;
    for (const ActionSpec& spec : WorkspaceCommandSpecs()) {
      if (!spec.command_name.empty()) {
        names.emplace_back(spec.command_name);
      }
    }
    return names;
  }();
  return kNames;
}

std::vector<std::string> WorkspaceDocumentedCommandUsages() {
  std::vector<std::string> usages;
  for (const ActionSpec& spec : WorkspaceCommandSpecs()) {
    if (spec.command_name.empty()) {
      continue;
    }
    usages.push_back(spec.command_usage.empty() ? std::string(spec.command_name)
                                                : std::string(spec.command_usage));
  }
  return usages;
}

}  // namespace microide::workspace
