#!/usr/bin/env python3
"""Generate the Unicode tables under src/util from Python's unicodedata.

  src/util/CaseFoldTable.inc      SimpleFoldCodepoint: simple lowercase mappings
  src/util/DisplayWidthTable.inc  CodepointDisplayWidth: zero-width and wide ranges

Case folding is str.lower for single-codepoint results (Unicode's simple
lowercase mapping), restricted to mappings whose UTF-8 encoding keeps its byte
length: every case-insensitive search path indexes the raw line by offsets into
its folded copy, so a fold that changed a scalar's byte width (KELVIN SIGN -> k,
OHM SIGN -> omega, 22 rare Latin letters) would desync them. Those stay unfolded;
the generator asserts the property.

Display width follows wcwidth's rules over the current Unicode data: nonspacing
and enclosing marks and format characters are zero width (SOFT HYPHEN excepted,
as in glibc), the Hangul conjoining jungseong/jongseong ranges are zero width
(they compose onto a preceding choseong), East Asian Wide and Fullwidth are two
columns — which is what puts the emoji in U+2600-27BF at two — and everything
else assigned is one. Controls are handled before the table.

Run from the repository root:  python3 tools/gen-unicode-tables.py
"""
import sys
import unicodedata


def runs_of_ranges(codepoints):
    """Collapse a sorted list of codepoints into [first, last] ranges."""
    ranges = []
    for cp in codepoints:
        if ranges and ranges[-1][1] + 1 == cp:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return ranges


def write_case_fold_table():
    mappings = []
    skipped = []
    for cp in range(0x80, 0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        upper = chr(cp)
        lower = upper.lower()
        if len(lower) != 1 or lower == upper:
            continue
        if len(upper.encode()) != len(lower.encode()):
            skipped.append((cp, ord(lower)))
            continue
        mappings.append((cp, ord(lower)))

    # Runs of (first, last, delta, stride): every stride-th codepoint in
    # [first, last] maps to itself + delta. Alternating upper/lower pairs
    # (Latin Extended-A style) are stride 2; contiguous alphabets stride 1.
    runs = []
    i = 0
    while i < len(mappings):
        first, lower = mappings[i]
        delta = lower - first
        last = first
        stride = 1
        j = i + 1
        if j < len(mappings) and mappings[j][1] - mappings[j][0] == delta and \
                mappings[j][0] - first in (1, 2):
            stride = mappings[j][0] - first
        while j < len(mappings) and mappings[j][0] == last + stride and \
                mappings[j][1] - mappings[j][0] == delta:
            last = mappings[j][0]
            j += 1
        runs.append((first, last, delta, stride))
        i = j

    lines = [
        "// Generated by tools/gen-unicode-tables.py from Unicode %s; do not edit." % unicodedata.unidata_version,
        "// Runs of {first, last, delta, stride}: every stride-th scalar in [first, last]",
        "// folds to itself + delta. %d mappings in %d runs; %d length-changing" % (len(mappings), len(runs), len(skipped)),
        "// mappings deliberately left out (see the generator's docstring).",
    ]
    for first, last, delta, stride in runs:
        lines.append("{0x%04X, 0x%04X, %d, %d}," % (first, last, delta, stride))
    with open("src/util/CaseFoldTable.inc", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("CaseFoldTable.inc: %d mappings as %d runs; skipped %d length-changing"
          % (len(mappings), len(runs), len(skipped)), file=sys.stderr)


def write_display_width_table():
    zero = []
    wide = []
    for cp in range(0xA0, 0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c = chr(cp)
        cat = unicodedata.category(c)
        if cat in ("Cn", "Co", "Cs"):
            continue
        if (cat in ("Mn", "Me", "Cf") and cp != 0x00AD) or 0x1160 <= cp <= 0x11FF \
                or 0xD7B0 <= cp <= 0xD7FF:
            zero.append(cp)
        elif unicodedata.east_asian_width(c) in ("W", "F"):
            wide.append(cp)
    zero_ranges = runs_of_ranges(zero)
    wide_ranges = runs_of_ranges(wide)
    lines = [
        "// Generated by tools/gen-unicode-tables.py from Unicode %s; do not edit." % unicodedata.unidata_version,
        "// Two sorted, disjoint {first, last} range lists: kZeroWidthRanges (%d scalars"
        % len(zero),
        "// in %d ranges) and kWideRanges (%d scalars in %d ranges). See the generator's"
        % (len(zero_ranges), len(wide), len(wide_ranges)),
        "// docstring for the rules.",
        "#define MICROIDE_ZERO_WIDTH_RANGES \\",
    ]
    for first, last in zero_ranges:
        lines.append("  {0x%04X, 0x%04X}, \\" % (first, last))
    lines[-1] = lines[-1][:-2]
    lines.append("#define MICROIDE_WIDE_RANGES \\")
    for first, last in wide_ranges:
        lines.append("  {0x%04X, 0x%04X}, \\" % (first, last))
    lines[-1] = lines[-1][:-2]
    with open("src/util/DisplayWidthTable.inc", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("DisplayWidthTable.inc: %d zero-width ranges, %d wide ranges"
          % (len(zero_ranges), len(wide_ranges)), file=sys.stderr)


def main():
    write_case_fold_table()
    write_display_width_table()


if __name__ == "__main__":
    main()
