#!/usr/bin/env python3
"""Generate tests/fixtures/terminal/pyte-reference.txt: random escape streams and
the screen + cursor pyte (a Python VT emulator) leaves behind, replayed by the
C++ test TerminalSession/ScreenAgreesWithPyteReference.

Setup:  python3 -m venv /tmp/pyte-venv && /tmp/pyte-venv/bin/pip install pyte
Run:    /tmp/pyte-venv/bin/python tools/gen-terminal-reference.py [cases] [seed]

Why the generator is deliberately narrow
----------------------------------------
pyte is not a bug-for-bug xterm clone, and this editor's emulator follows xterm.
The two agree on cursor addressing and the CSI editing/erase operators, so those
are what the generator exercises. It stays away from the places they diverge:

  * DECAWM pending wrap. pyte has no last-column flag; it lets cursor.x reach
    `columns` and wraps on the next printable, so the flag "survives" a cursor
    move (CUD/CUP/...) — which xterm and this emulator clear. Verified against
    xterm semantics on a randomized run: every last-column divergence was pyte,
    not the emulator. So the cursor is kept strictly left of the last column
    here; the pending-wrap path has its own hand-written tests.
  * Scrolling and margins. A bare LF, NEL, IND/RI at the margin, and DECSTBM
    scroll timing differ (some are this emulator's recorded deliberate
    deviations); the generator never scrolls the screen.
  * Tab-stop clamping at a narrow width, wide/combining glyphs, origin/insert
    mode, the alternate screen.

Format, one case per block:
  case <id> rows=<r> cols=<c>
  in <hex bytes>
  | <row text>          (exactly <r> lines, trailing blanks trimmed by the test)
  cursor <y> <x>
"""
import random
import sys

import pyte

LETTERS = "abcdefghijklmnopqrstuvwxyz0123456789.,-#/"


def gen_case(rng, rows, cols, ops):
    screen = pyte.Screen(cols, rows)
    stream = pyte.ByteStream(screen)
    out = bytearray()
    last_col = cols - 2  # highest column the cursor may occupy — never the last

    def emit(b):
        out.extend(b)
        stream.feed(bytes(b))

    for _ in range(ops):
        k = rng.randrange(18)
        if k < 6:
            room = last_col - screen.cursor.x
            if room <= 0:
                continue
            n = rng.randrange(1, room + 1)
            emit("".join(rng.choice(LETTERS) for _ in range(n)).encode())
        elif k == 6:
            emit(b"\r")
        elif k == 7:
            if screen.cursor.x > 0:
                emit(b"\x08")
        elif k == 8:  # CUP
            emit(b"\x1b[%d;%dH" % (rng.randrange(1, rows + 1), rng.randrange(1, last_col + 1)))
        elif k == 9:  # CUF, capped short of the last column
            room = last_col - screen.cursor.x
            if room > 0:
                emit(b"\x1b[%dC" % rng.randrange(1, room + 1))
        elif k == 10:  # CUB
            if screen.cursor.x > 0:
                emit(b"\x1b[%dD" % rng.randrange(1, screen.cursor.x + 1))
        elif k == 11:  # CUU
            if screen.cursor.y > 0:
                emit(b"\x1b[%dA" % rng.randrange(1, screen.cursor.y + 1))
        elif k == 12:  # CUD, never onto the last row (no scroll)
            room = rows - 1 - screen.cursor.y
            if room > 0:
                emit(b"\x1b[%dB" % rng.randrange(1, room + 1))
        elif k == 13:  # CHA
            emit(b"\x1b[%dG" % rng.randrange(1, last_col + 1))
        elif k == 14:  # VPA
            emit(b"\x1b[%dd" % rng.randrange(1, rows + 1))
        elif k == 15:  # ED
            emit(b"\x1b[%dJ" % rng.choice([0, 1, 2]))
        elif k == 16:  # EL
            emit(b"\x1b[%dK" % rng.choice([0, 1, 2]))
        else:  # ICH / DCH / ECH
            emit(b"\x1b[%d" % rng.randrange(1, cols) + rng.choice([b"@", b"P", b"X"]))
    return bytes(out), screen.display, (screen.cursor.y, min(screen.cursor.x, cols - 1))


def main():
    cases = int(sys.argv[1]) if len(sys.argv) > 1 else 600
    seed = int(sys.argv[2]) if len(sys.argv) > 2 else 20260905
    rng = random.Random(seed)
    lines = ["# Generated by tools/gen-terminal-reference.py seed=%d; do not edit." % seed]
    for i in range(cases):
        rows = rng.randrange(4, 10)
        cols = rng.randrange(6, 20)
        ops = rng.randrange(4, 32)
        data, display, (cy, cx) = gen_case(rng, rows, cols, ops)
        lines.append("case %d rows=%d cols=%d" % (i, rows, cols))
        lines.append("in " + data.hex())
        for row in display:
            lines.append("| " + row)
        lines.append("cursor %d %d" % (cy, cx))
    with open("tests/fixtures/terminal/pyte-reference.txt", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d cases" % cases)


if __name__ == "__main__":
    main()
