#!/usr/bin/env python3
"""Generate src/util/CaseFoldTable.inc: Unicode simple lowercase mappings as runs.

SimpleFoldCodepoint (src/util/StringUtil.cpp) folds through this table. It is
derived from Python's unicodedata (str.lower for single-codepoint results, which
is Unicode's simple lowercase mapping), restricted to mappings whose UTF-8
encoding keeps its byte length: every case-insensitive search path indexes the
raw line by offsets into its folded copy, so a fold that changed a scalar's byte
width (KELVIN SIGN -> k, OHM SIGN -> omega, 22 rare Latin letters) would desync
them. Those stay unfolded; the generator asserts the property.

Run from the repository root:  python3 tools/gen-case-fold-table.py
"""
import sys
import unicodedata

def main():
    mappings = []
    skipped = []
    for cp in range(0x80, 0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        upper = chr(cp)
        lower = upper.lower()
        if len(lower) != 1 or lower == upper:
            continue
        if len(upper.encode()) != len(lower.encode()):
            skipped.append((cp, ord(lower)))
            continue
        mappings.append((cp, ord(lower)))

    # Runs of (first, last, delta, stride): every stride-th codepoint in
    # [first, last] maps to itself + delta. Alternating upper/lower pairs
    # (Latin Extended-A style) are stride 2; contiguous alphabets stride 1.
    runs = []
    i = 0
    while i < len(mappings):
        first, lower = mappings[i]
        delta = lower - first
        last = first
        stride = 1
        j = i + 1
        if j < len(mappings) and mappings[j][1] - mappings[j][0] == delta and \
                mappings[j][0] - first in (1, 2):
            stride = mappings[j][0] - first
        while j < len(mappings) and mappings[j][0] == last + stride and \
                mappings[j][1] - mappings[j][0] == delta:
            last = mappings[j][0]
            j += 1
        runs.append((first, last, delta, stride))
        i = j

    lines = [
        "// Generated by tools/gen-case-fold-table.py from Unicode %s; do not edit." % unicodedata.unidata_version,
        "// Runs of {first, last, delta, stride}: every stride-th scalar in [first, last]",
        "// folds to itself + delta. %d mappings in %d runs; %d length-changing" % (len(mappings), len(runs), len(skipped)),
        "// mappings deliberately left out (see the generator's docstring).",
    ]
    for first, last, delta, stride in runs:
        lines.append("{0x%04X, 0x%04X, %d, %d}," % (first, last, delta, stride))
    with open("src/util/CaseFoldTable.inc", "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d mappings as %d runs; skipped %d length-changing" % (len(mappings), len(runs), len(skipped)), file=sys.stderr)

if __name__ == "__main__":
    main()
